### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Th3OnlyN00b** [david-fisher/320-S19-Track1#5]
In an effort to organize our issues, please make a custom label for each team and label your issues as such. Try to choose different color labels for your teams. This will allow us to search for issues by team and stop clutter.

**Comment by david-fisher** [comment]
Or you could just create a label for each team on your track that they could then use...

**Comment by david-fisher** [comment]
When issues are created, they should be assigned to the Members Only project (to the right) so that they will show up on the Kanban board as ToDos...

**Comment by Th3OnlyN00b** [comment]
The labels have been created.
