### ISSUE TITLE
Collect Pizza money and add types of desired pizza to github

### ISSUE THREAD

**Issue by Th3OnlyN00b** [david-fisher/320-S19-Track1#79]
Use the menu [here](https://www.amhersthouseofpizza.com/menue) 

Please add the pizza your team wants [here](https://docs.google.com/spreadsheets/d/140jALcxEfCFnr76C5_qBO9pfExho5tQxfIEdGlDPUF0/edit#gid=0) in the "Team Red" section. Tip/Tax included in the total in column B.

Cole will take care of ordering, please collect your team's money and deliver it to him.  All finances are public and on the google sheets.

**Comment by david-fisher** [comment]
Safari users should open the menu link in chrome, it is an Epic Fail in Safari...
