### ISSUE TITLE
Decide on team's pizza order, collect money, and fill out document.

### ISSUE THREAD

**Issue by Th3OnlyN00b** [david-fisher/320-S19-Track1#82]
Use the menu [here](https://www.amhersthouseofpizza.com/menue) 

Please add the pizza your team wants [here](https://docs.google.com/spreadsheets/d/140jALcxEfCFnr76C5_qBO9pfExho5tQxfIEdGlDPUF0/edit#gid=0) in your team's respective order section and collect the required total (Column B). Tip is calculated already.

ONLY EDIT THE GREEN TILES. Do not edit payments. That is for me to edit when you actually hand me money.

I will take care of ordering, please collect your team's money and deliver it to me.  All finances are public and on the google sheets.

**Comment by david-fisher** [comment]
Safari users should open the menu link in chrome, it is an Epic Fail in Safari...
