### ISSUE TITLE
Decide pizza order, collect $, fill out doc

### ISSUE THREAD

**Issue by Th3OnlyN00b** [david-fisher/320-S19-Track1#84]
Not really sure if you wanted to be involved, but I figured I'd offer for you and the PMs. Feel free to close the issue if you'd rather not be involved.

Use the menu [here](https://www.amhersthouseofpizza.com/menue) 

Please add the pizza your team wants [here](https://docs.google.com/spreadsheets/d/140jALcxEfCFnr76C5_qBO9pfExho5tQxfIEdGlDPUF0/edit#gid=0) in the "PMs/Fisher's order" section. Tip and Tax included in total, which is in column B.

Cole will take care of ordering, please collect your team's money and deliver it to him.  All finances are public and on the google sheets.

**Comment by david-fisher** [comment]
Safari users should open the menu link in chrome, it is an Epic Fail in Safari...

**Comment by david-fisher** [comment]
I will keep an eye on your progress and sort out what budgetary contribution to make when the various contributions are totaled up.

**Comment by Th3OnlyN00b** [comment]
Sounds good to me

**Comment by david-fisher** [comment]
PMs should not feel the need to contribute $ to the activity. They should certainly express their order preferences.
